/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Liveness check */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Service is up */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              /** @enum {string} */
              status: 'ok';
            };
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/genres': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List selectable genres and themes */
    get: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Genres/themes available for taste selection */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Genre'][];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/anime/search': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Search the catalog by title (autocomplete for favorites) */
    get: {
      parameters: {
        query: {
          /** @description Partial title */
          q: string;
        };
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody?: never;
      responses: {
        /** @description Matching titles (capped, e.g. 10) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['AnimeSummary'][];
          };
        };
        /** @description Missing or invalid query */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/recommendations': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Generate banded anime recommendations from a taste profile */
    post: {
      parameters: {
        query?: never;
        header?: never;
        path?: never;
        cookie?: never;
      };
      requestBody: {
        content: {
          'application/json': components['schemas']['TasteProfile'];
        };
      };
      responses: {
        /** @description Ranked, banded recommendations (reasons present when AI assist is available) */
        200: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': {
              results: components['schemas']['Recommendation'][];
              /** @description false when the deterministic fallback produced the ordering/bands */
              aiAssisted: boolean;
            };
          };
        };
        /** @description Empty/invalid taste profile (e.g. no genres selected) */
        400: {
          headers: {
            [name: string]: unknown;
          };
          content: {
            'application/json': components['schemas']['Error'];
          };
        };
      };
    };
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Genre: {
      id: number;
      name: string;
      /** @enum {string} */
      kind: 'GENRE' | 'THEME' | 'DEMOGRAPHIC';
    };
    AnimeSummary: {
      id: number;
      title: string;
      imageUrl?: string | null;
    };
    TasteProfile: {
      genreIds: number[];
      /** @default [] */
      favoriteAnimeIds: number[];
      /**
       * @description May be true only after the visitor self-confirms they are 18+
       * @default false
       */
      includeExplicit: boolean;
    };
    Recommendation: {
      id: number;
      title: string;
      titleEnglish?: string | null;
      synopsis?: string | null;
      imageUrl?: string | null;
      genres: string[];
      /**
       * @description Displayed as "Chef's pick" / "Recommended" / "Worth a try"
       * @enum {string}
       */
      band: 'CHEFS_PICK' | 'RECOMMENDED' | 'WORTH_A_TRY';
      /** @description AI explanation; null when the AI assist is unavailable */
      reason?: string | null;
    };
    Error: {
      message: string;
      code?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
